// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChambersDataModel.Entities
{
    public partial class Bauexcursion
    {
        public string Building { get; set; }
        public int LAreaId { get; set; }
        public int LUnitId { get; set; }
        public string Area { get; set; }
        public string Unit { get; set; }
        public int? TagId { get; set; }
        public string TagName { get; set; }
        public int TagExcNbr { get; set; }
        public int? StepLogId { get; set; }
        public DateTime? RampInDate { get; set; }
        public double? RampInValue { get; set; }
        public DateTime? FirstExcDate { get; set; }
        public double? FirstExcValue { get; set; }
        public DateTime? LastExcDate { get; set; }
        public double? LastExcValue { get; set; }
        public DateTime? RampOutDate { get; set; }
        public double? RampOutValue { get; set; }
        public int HiPointsCt { get; set; }
        public int LowPointsCt { get; set; }
        public double? MinThreshold { get; set; }
        public double? MaxThreshold { get; set; }
        public double? MinValue { get; set; }
        public double? MaxValue { get; set; }
        public double? AvergValue { get; set; }
        public double? StdDevValue { get; set; }
        public int? Duration { get; set; }
        public int? ThresholdDuration { get; set; }
        public double? SetPoint { get; set; }
        public string STagDesc { get; set; }
        public string SEgu { get; set; }
        public DateTime? StageDeprecatedDate { get; set; }
        public DateTime? StageDateDeprecatedDate { get; set; }
        public DateTime? ProductionDate { get; set; }
        public string ExcType { get; set; }
        public string StructDuration { get; set; }
    }
}