// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChambersDataModel.Entities
{
    public partial class BuildingsAreasUnit
    {
        public int LBuildingId { get; set; }
        public string Building { get; set; }
        public int LAreaId { get; set; }
        public string Area { get; set; }
        public int LUnitId { get; set; }
        public string Unit { get; set; }
        public int LTagId { get; set; }
        public string Tag { get; set; }
        public string SEgu { get; set; }
        public string TagDesc { get; set; }
    }
}