// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using ChambersDataModel.Entities;

namespace ChambersDataModel.Entities
{
    public partial class ChambersDbContext
    {

        [DbFunction("fnGetOverlappingDates", "dbo")]
        public IQueryable<fnGetOverlappingDatesResult> fnGetOverlappingDates(DateTime? StartDate1, DateTime? endDate1, DateTime? StartDate2, DateTime? endDate2)
        {
            return FromExpression(() => fnGetOverlappingDates(StartDate1, endDate1, StartDate2, endDate2));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<fnGetOverlappingDatesResult>().HasNoKey();
        }
    }
}
