// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChambersDataModel.Entities
{
    public partial class CompressedPoint
    {
        public string Tag { get; set; }
        public DateTime Time { get; set; }
        public double Value { get; set; }
    }
}