// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChambersDataModel.Entities
{
    public partial class DefaultPointsPace
    {
        public int TagId { get; set; }
        public DateTime? NextStepStartDate { get; set; }
    }
}