// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChambersDataModel.Entities
{
    public partial class ExcursionPoint
    {
        public int PointNbr { get; set; }
        public int TagId { get; set; }
        public string TagName { get; set; }
        public DateTime ValueDate { get; set; }
        public double Value { get; set; }
        public int ExcNbr { get; set; }
        public string ExcType { get; set; }
        public int StepLogId { get; set; }

        public virtual ExcursionType ExcTypeNavigation { get; set; }
        public virtual PointsStepsLog StepLog { get; set; }
    }
}