// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChambersDataModel.Entities
{
    public partial class ExcursionType
    {
        public ExcursionType()
        {
            ExcursionPoints = new HashSet<ExcursionPoint>();
        }

        public string ExcType { get; set; }
        public string Predicate { get; set; }
        public string ExcDescription { get; set; }

        public virtual ICollection<ExcursionPoint> ExcursionPoints { get; set; }
    }
}