// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChambersDataModel.Entities
{
    public partial class Excursion
    {
        public int TagId { get; set; }
        public int ExcursionNbr { get; set; }
        public DateTime RampInDateTime { get; set; }
        public DateTime RampOutDateTime { get; set; }
        public int? RampInPointId { get; set; }
        public int? RampOutPointId { get; set; }
    }
}