// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ChambersDataModel.Entities
{
    public partial class fnGetExcursionsCountsResult
    {
        public string TagName { get; set; }
        public int? HiExcsCount { get; set; }
        public int? LowExcsCount { get; set; }
    }
}
