// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ChambersDataModel.Entities
{
    public partial class MergeIncompleteCyclesResult
    {
        public int? CycleId { get; set; }
        public string TagName { get; set; }
        public int? TagExcNbr { get; set; }
        public DateTime? RampInDate { get; set; }
        public double? RampInValue { get; set; }
        public DateTime? RampOutDate { get; set; }
        public int? LowPointsCt { get; set; }
        public int? HiPointsCt { get; set; }
    }
}
