// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ChambersDataModel.Entities
{
    public partial class spGetStatsResult
    {
        public string TagName { get; set; }
        public int TagExcNbr { get; set; }
        public int? TagId { get; set; }
        public double? MinValue { get; set; }
        public double? MaxValue { get; set; }
        public double? AverageValue { get; set; }
        public double? StdDeviation { get; set; }
    }
}
