// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChambersDataModel.Entities
{
    public partial class Stage
    {
        public Stage()
        {
            StagesDates = new HashSet<StagesDate>();
        }

        public int StageId { get; set; }
        public int TagId { get; set; }
        public string StageName { get; set; }
        public double MinThreshold { get; set; }
        public double MaxThreshold { get; set; }
        public double? TimeStep { get; set; }
        public DateTime? ProductionDate { get; set; }
        public DateTime? DeprecatedDate { get; set; }

        public virtual Tag Tag { get; set; }
        public virtual ICollection<StagesDate> StagesDates { get; set; }
    }
}